# Generated by Django 5.2.6 on 2025-10-07 15:05

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_consanguineous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfamily',
            name='is_consanguineous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='age_of_onset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='age_of_onset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('aminoacid_change', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('alternate', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('effect_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('acmg_evidence', models.CharField(blank=True, max_length=100, null=True)),
                ('acmg_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical variant',
                'verbose_name_plural': 'historical variants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('aminoacid_change', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('alternate', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('effect_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('acmg_evidence', models.CharField(blank=True, max_length=100, null=True)),
                ('acmg_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_variants', to='lab.analysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='lab.individual')),
            ],
            bases=(lab.models.HistoryMixin, models.Model),
        ),
    ]
