# Generated by Django 5.2.8 on 2025-11-27 11:02

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0002_remove_variant_analysis_remove_variant_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_variants', to='lab.analysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='lab.individual')),
            ],
            options={
                'ordering': ['chromosome', 'start'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CNV',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='variant.variant')),
                ('cnv_type', models.CharField(choices=[('deletion', 'Deletion'), ('duplication', 'Duplication'), ('loss', 'Loss'), ('gain', 'Gain')], max_length=50)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
            ],
            bases=('variant.variant',),
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='variant.variant')),
                ('repeat_unit', models.CharField(max_length=50)),
                ('repeat_count', models.IntegerField()),
            ],
            bases=('variant.variant',),
        ),
        migrations.CreateModel(
            name='SNV',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='variant.variant')),
                ('reference', models.CharField(max_length=255)),
                ('alternate', models.CharField(max_length=255)),
            ],
            bases=('variant.variant',),
        ),
        migrations.CreateModel(
            name='SV',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='variant.variant')),
                ('sv_type', models.CharField(choices=[('inversion', 'Inversion'), ('translocation', 'Translocation'), ('insertion', 'Insertion'), ('deletion', 'Deletion'), ('duplication', 'Duplication')], max_length=50)),
                ('breakpoints', models.JSONField(blank=True, help_text='Detailed breakpoint coordinates', null=True)),
            ],
            bases=('variant.variant',),
        ),
        migrations.CreateModel(
            name='HistoricalCNV',
            fields=[
                ('variant_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='variant.variant')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('cnv_type', models.CharField(choices=[('deletion', 'Deletion'), ('duplication', 'Duplication'), ('loss', 'Loss'), ('gain', 'Gain')], max_length=50)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical cnv',
                'verbose_name_plural': 'historical cnvs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRepeat',
            fields=[
                ('variant_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='variant.variant')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('repeat_unit', models.CharField(max_length=50)),
                ('repeat_count', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical repeat',
                'verbose_name_plural': 'historical repeats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSNV',
            fields=[
                ('variant_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='variant.variant')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('reference', models.CharField(max_length=255)),
                ('alternate', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical snv',
                'verbose_name_plural': 'historical snvs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSV',
            fields=[
                ('variant_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='variant.variant')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('sv_type', models.CharField(choices=[('inversion', 'Inversion'), ('translocation', 'Translocation'), ('insertion', 'Insertion'), ('deletion', 'Deletion'), ('duplication', 'Duplication')], max_length=50)),
                ('breakpoints', models.JSONField(blank=True, help_text='Detailed breakpoint coordinates', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical sv',
                'verbose_name_plural': 'historical svs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
            ],
            options={
                'verbose_name': 'historical variant',
                'verbose_name_plural': 'historical variants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='e.g. myvariant, vep, genebe', max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='variant.variant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('variant', 'source', 'source_version')},
            },
        ),
    ]
