# Generated by Django 6.0rc1 on 2026-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcnv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldelins',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalrepeat',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsnv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvariant',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variant',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('hetpl', 'Heteroplasmy'), ('homoplasmy', 'Homoplasmy')], max_length=20),
        ),
    ]
