# Generated by Django 5.2.8 on 2025-11-27 12:12

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnv',
            name='cnv_type',
            field=models.CharField(choices=[('loss', 'Loss'), ('gain', 'Gain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcnv',
            name='cnv_type',
            field=models.CharField(choices=[('loss', 'Loss'), ('gain', 'Gain')], max_length=50),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('pathogenic', 'Pathogenic'), ('likely_pathogenic', 'Likely Pathogenic'), ('vus', 'VUS'), ('likely_benign', 'Likely Benign'), ('benign', 'Benign')], max_length=50)),
                ('inheritance', models.CharField(choices=[('ad', 'Autosomal Dominant'), ('ar', 'Autosomal Recessive'), ('x_linked', 'X-linked'), ('mitochondrial', 'Mitochondrial'), ('de_novo', 'De Novo'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='variant.variant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClassification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('classification', models.CharField(choices=[('pathogenic', 'Pathogenic'), ('likely_pathogenic', 'Likely Pathogenic'), ('vus', 'VUS'), ('likely_benign', 'Likely Benign'), ('benign', 'Benign')], max_length=50)),
                ('inheritance', models.CharField(choices=[('ad', 'Autosomal Dominant'), ('ar', 'Autosomal Recessive'), ('x_linked', 'X-linked'), ('mitochondrial', 'Mitochondrial'), ('de_novo', 'De Novo'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='variant.variant')),
            ],
            options={
                'verbose_name': 'historical classification',
                'verbose_name_plural': 'historical classifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
