# Generated by Django 6.0rc1 on 2026-02-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_analysis_type_remove_historicalanalysis_type_and_more'),
        ('variant', '0002_alter_historicalcnv_zygosity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcnv',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalrepeat',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalsnv',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalsv',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalvariant',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='analysis',
        ),
        migrations.AddField(
            model_name='historicalcnv',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='historicalrepeat',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='historicalsnv',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='historicalsv',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='variant',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_variants', to='lab.pipeline'),
        ),
    ]
