# Generated by Django 6.0rc1 on 2026-02-10 13:17
# Amended: added RunPython data migration to copy variant.analysis.pipeline
# → variant.pipeline before the analysis FK column is dropped.

import django.db.models.deletion
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Data-migration helper
# ---------------------------------------------------------------------------

def migrate_variants_to_pipelines(apps, schema_editor):
    """
    By the time this migration runs, lab/0007 has already:
      - created a Pipeline for every old Analysis
      - set analysis.pipeline on every Analysis row

    All we need to do here is copy that reference one level up:
        variant.pipeline = variant.analysis.pipeline

    Variants that already have no analysis (null) stay null.
    """
    Variant = apps.get_model("variant", "Variant")

    # Bulk-update in a single query using a subquery join.
    # We iterate instead of bulk UPDATE…FROM because Django's ORM
    # portable cross-DB approach is a loop with filter+update.
    for variant in (
        Variant.objects
        .filter(analysis__isnull=False, analysis__pipeline__isnull=False)
        .select_related("analysis")
    ):
        Variant.objects.filter(pk=variant.pk).update(
            pipeline_id=variant.analysis.pipeline_id
        )


def reverse_noop(apps, schema_editor):
    """Reverse is intentionally a no-op."""


# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_remove_analysis_type_remove_historicalanalysis_type_and_more"),
        ("variant", "0002_alter_historicalcnv_zygosity_and_more"),
    ]

    operations = [
        # ── 1. Add variant.pipeline FK first (nullable) so the data
        #       migration can fill it in before the old analysis FK is gone.
        migrations.AddField(
            model_name="variant",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="found_variants",
                to="lab.pipeline",
            ),
        ),
        # ── 2. THE DATA MIGRATION ─────────────────────────────────────────
        #       Copies variant.analysis.pipeline → variant.pipeline for every
        #       variant that had an analysis.  Safe to drop analysis FK after.
        migrations.RunPython(migrate_variants_to_pipelines, reverse_noop),
        # ── 3. Drop the old analysis FK from the live Variant table ────────
        migrations.RemoveField(
            model_name="variant",
            name="analysis",
        ),
        # ── 4. Historical-model bookkeeping (order does not matter for data) ─
        migrations.AddField(
            model_name="historicalcnv",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicalrepeat",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicalsnv",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicalsv",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicalvariant",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        migrations.RemoveField(
            model_name="historicalcnv",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalrepeat",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalsnv",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalsv",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalvariant",
            name="analysis",
        ),
    ]
