# Generated by Django 6.0rc1 on 2025-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_analysisreport_historicalanalysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='analysis_reports/previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='historicalanalysisreport',
            name='preview_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
