# Generated by Django 5.2.8 on 2025-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_alter_cnv_cnv_type_alter_historicalcnv_cnv_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgnc_id', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('alias_symbol', models.TextField(blank=True)),
                ('alias_name', models.TextField(blank=True)),
                ('ensembl_gene_id', models.CharField(blank=True, max_length=50)),
                ('entrez_id', models.CharField(blank=True, max_length=50)),
                ('omim_id', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='variants', to='variant.gene'),
        ),
    ]
