# Generated by Django 5.2.8 on 2025-11-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_variant_analysis_remove_variant_created_by_and_more'),
        ('variant', '0003_gene_variant_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcnv',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='historicalrepeat',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='historicalsnv',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='historicalsv',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='variant',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.status'),
        ),
    ]
