# Generated by Django 6.0rc1 on 2025-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_analysisreport_preview_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='preview_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='analysis_reports/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='historicalanalysisreport',
            name='preview_file',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
