# Generated by Django 6.0rc1 on 2026-03-04 12:22

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_pipeline_add_locations'),
        ('variant', '0004_uppercase_snv_alleles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='delins',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='variant.variant')),
                ('reference', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')])),
                ('alternate', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')])),
            ],
            bases=('variant.variant',),
        ),
        migrations.AlterField(
            model_name='historicalsnv',
            name='alternate',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalsnv',
            name='reference',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')]),
        ),
        migrations.AlterField(
            model_name='snv',
            name='alternate',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')]),
        ),
        migrations.AlterField(
            model_name='snv',
            name='reference',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')]),
        ),
        migrations.CreateModel(
            name='Historicaldelins',
            fields=[
                ('variant_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='variant.variant')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assembly_version', models.CharField(default='hg38', max_length=10)),
                ('chromosome', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('zygosity', models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous')], max_length=20)),
                ('reference', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')])),
                ('alternate', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_allele', message='Alleles must consist only of the uppercase characters A, T, G, or C.', regex='^[ATGC]+$')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual')),
                ('pipeline', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status')),
            ],
            options={
                'verbose_name': 'historical delins',
                'verbose_name_plural': 'historical delinss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
