# Generated by Django 6.0rc1 on 2026-03-04 12:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_variant_analysis_from_pipeline(apps, schema_editor):
    """
    Populate Variant.analysis from Variant.pipeline where possible.

    For each Variant that currently points to a Pipeline, we try to find an
    Analysis on that Pipeline and assign the most recent one by
    performed_date/id.
    """
    Variant = apps.get_model("variant", "Variant")
    Analysis = apps.get_model("lab", "Analysis")

    for variant in Variant.objects.filter(pipeline__isnull=False).only("pk", "pipeline_id"):
        analysis = (
            Analysis.objects.filter(pipeline_id=variant.pipeline_id)
            .order_by("-performed_date", "-id")
            .first()
        )
        if analysis is not None:
            Variant.objects.filter(pk=variant.pk).update(analysis_id=analysis.pk)


def noop_reverse(apps, schema_editor):
    # We don't try to reconstruct pipeline from analysis.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_pipeline_add_locations'),
        ('variant', '0005_delins_alter_historicalsnv_alternate_and_more'),
    ]

    operations = [
        # 1) Add the new analysis FKs while pipeline still exists
        migrations.AddField(
            model_name='historicalcnv',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicaldelins',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalrepeat',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalsnv',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalsv',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='variant',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_variants', to='lab.analysis'),
        ),
        # 2) Backfill Variant.analysis using the existing pipeline link
        migrations.RunPython(migrate_variant_analysis_from_pipeline, noop_reverse),
        # 3) Drop the old pipeline FKs now that analysis is in place
        migrations.RemoveField(
            model_name='historicalcnv',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicaldelins',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalrepeat',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalsnv',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalsv',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalvariant',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='pipeline',
        ),
    ]
