# Generated by Django 5.2.8 on 2025-11-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_historicalannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcnv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalrepeat',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsnv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsv',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='variant',
            name='zygosity',
            field=models.CharField(choices=[('het', 'Heterozygous'), ('hom', 'Homozygous'), ('hemi', 'Hemizygous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
