# Generated by Django 5.2.8 on 2025-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_historicalcnv_zygosity_historicalrepeat_zygosity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='gene_family',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='locus_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gene',
            name='locus_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gene',
            name='prev_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='prev_symbol',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='pubmed_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='refseq_accession',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='uniprot_ids',
            field=models.TextField(blank=True),
        ),
    ]
