# Generated by Django 6.0rc1 on 2026-03-09

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_remove_analysis_status_and_more'),
        ('variant', '0006_remove_historicalcnv_pipeline_and_more'),
    ]

    operations = [
        # Add the new TaggableManager field first (virtual, no DB column)
        migrations.AddField(
            model_name='variant',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        # Then remove the old status FK columns
        migrations.RemoveField(model_name='historicalcnv', name='status'),
        migrations.RemoveField(model_name='historicaldelins', name='status'),
        migrations.RemoveField(model_name='historicalrepeat', name='status'),
        migrations.RemoveField(model_name='historicalsnv', name='status'),
        migrations.RemoveField(model_name='historicalsv', name='status'),
        migrations.RemoveField(model_name='historicalvariant', name='status'),
        migrations.RemoveField(model_name='variant', name='status'),
    ]
