# Generated by Django 5.2.5 on 2025-08-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='term',
            new_name='ontologies__ontolog_943e40_idx',
            old_name='ontologies_te_ontolog_8b8c8c_idx',
        ),
    ]
