# Generated by Django 6.0rc1 on 2026-03-12 10:19

import django.db.models.deletion
import lab.models
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lab', '0001_initial'),
        ('ontologies', '0001_initial'),
        ('variant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='reports', to='variant.variant'),
        ),
        migrations.AddField(
            model_name='analysisrequestform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_analysis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='lab.analysistype'),
        ),
        migrations.AddField(
            model_name='crossidentifier',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysistype'),
        ),
        migrations.AddField(
            model_name='historicalanalysisreport',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisrequestform',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisrequestform',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysistype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysistype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrossidentifier',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrossidentifier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfamily',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfamily',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidentifiertype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidentifiertype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.family'),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstitution',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstitution',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='private_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, note is visible only to this user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpipelinetype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpipelinetype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('emails', models.JSONField(blank=True, default=list, help_text='Ordered email addresses associated with this contact.')),
                ('phones', models.JSONField(blank=True, default=list, help_text='Ordered phone numbers associated with this contact.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('emails', models.JSONField(blank=True, default=list, help_text='Ordered email addresses associated with this contact.')),
                ('phones', models.JSONField(blank=True, default=list, help_text='Ordered phone numbers associated with this contact.')),
                ('notes', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='isolation_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.contact'),
        ),
        migrations.AddField(
            model_name='historicalsampletype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsampletype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstatusgroup',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalstatusgroup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identifiertype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_id_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrossidentifier',
            name='id_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.identifiertype'),
        ),
        migrations.AddField(
            model_name='crossidentifier',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.identifiertype'),
        ),
        migrations.AddField(
            model_name='individual',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_individuals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individuals', to='lab.family'),
        ),
        migrations.AddField(
            model_name='individual',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_father', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='hpo_terms',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ontology__type': 1}, related_name='individuals', to='ontologies.term'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_mother', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='physicians',
            field=models.ManyToManyField(blank=True, related_name='patients', to='lab.contact'),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='individual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='father',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='mother',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='historicalcrossidentifier',
            name='individual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='historicalanalysisrequestform',
            name='individual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='crossidentifier',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_ids', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='analysisrequestform',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_request_forms', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='institution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='institutions_as_staff', to='lab.contact'),
        ),
        migrations.AddField(
            model_name='individual',
            name='institution',
            field=models.ManyToManyField(related_name='individuals', to='lab.institution'),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.institution'),
        ),
        migrations.AddField(
            model_name='crossidentifier',
            name='institution',
            field=models.ManyToManyField(blank=True, to='lab.institution'),
        ),
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='note',
            name='private_owner',
            field=models.ForeignKey(blank=True, help_text='If set, note is visible only to this user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisreport',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pipeline_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinetype',
            name='parent_types',
            field=models.ManyToManyField(blank=True, related_name='subtypes', to='lab.pipelinetype'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.pipelinetype'),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipelinetype'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_info',
            field=models.JSONField(blank=True, default=list, help_text='Ordered clinician contact values imported from spreadsheets.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signer_block_text',
            field=models.TextField(blank=True, default='', help_text='Multiline signer block inserted into generated reports.'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='individuals',
            field=models.ManyToManyField(related_name='projects', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.project'),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lab.individual'),
        ),
        migrations.AddField(
            model_name='sample',
            name='isolation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='isolated_samples', to='lab.contact'),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='sample',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.sample'),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.sampletype'),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.sampletype'),
        ),
        migrations.AddField(
            model_name='status',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='previous_status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Stores the primary task status before it was last completed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='statusgroup',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='status',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Statuses in the same group are mutually exclusive — selecting one removes the others.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='lab.statusgroup'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Statuses in the same group are mutually exclusive — selecting one removes the others.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.statusgroup'),
        ),
        migrations.AddField(
            model_name='taggedstatus',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='taggedstatus',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='lab.status'),
        ),
        migrations.AddField(
            model_name='sample',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='project',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='individual',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.ForeignKey(blank=True, help_text='Stores the primary task status before it was last completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_previous_status', to='lab.status'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='lab.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_performed', to='lab.institution'),
        ),
        migrations.AddField(
            model_name='test',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='lab.sample'),
        ),
        migrations.AddField(
            model_name='test',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='lab.test'),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='test',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.test'),
        ),
        migrations.AddField(
            model_name='testtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_coverage_20x_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_filtering_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_limitations_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_mean_depth_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_method_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_negative_result_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_positive_comment_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testtype',
            name='default_total_reads_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testtype',
            name='negative_report_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testtype',
            name='positive_report_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.testtype'),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='test_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.testtype'),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_coverage_20x_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_filtering_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_limitations_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_mean_depth_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_method_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_negative_result_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_positive_comment_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='default_total_reads_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='negative_report_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltesttype',
            name='positive_report_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PlotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(max_length=100)),
                ('query_config', models.JSONField(default=dict)),
                ('notebook_filename', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plot_templates', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlotTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(max_length=100)),
                ('query_config', models.JSONField(default=dict)),
                ('notebook_filename', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plot template',
                'verbose_name_plural': 'historical plot templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('col_span', models.IntegerField(default=1)),
                ('row_span', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.plottemplate')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDashboardWidget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('col_span', models.IntegerField(default=1)),
                ('row_span', models.IntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.plottemplate')),
            ],
            options={
                'verbose_name': 'historical dashboard widget',
                'verbose_name_plural': 'historical dashboard widgets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='crossidentifier',
            unique_together={('individual', 'id_type')},
        ),
        migrations.AlterUniqueTogether(
            name='statusgroup',
            unique_together={('name', 'content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='taggedstatus',
            unique_together={('content_type', 'object_id', 'tag')},
        ),
    ]
