# Generated by Django 5.1.6 on 2025-03-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="tests",
            new_name="test_types",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="test",
            new_name="test_type",
        ),
    ]
