# Generated by Django 6.0rc1 on 2026-03-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalanalysisreport',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='lab.analysis'),
        ),
        migrations.AddField(
            model_name='historicalanalysisreport',
            name='analysis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.analysis'),
        ),
    ]
