# Generated by Django 5.1.6 on 2025-03-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_rename_tests_sample_test_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="test_types",
        ),
    ]
