# Generated by Django 4.2.23 on 2025-12-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_family_is_consanguineous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='individual',
        ),
        migrations.DeleteModel(
            name='HistoricalVariant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
