# Generated by Django 4.2.23 on 2025-12-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_variant_analysis_remove_variant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='previous_status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Stores the task status before it was last completed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.ForeignKey(blank=True, help_text='Stores the task status before it was last completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_previous_status', to='lab.status'),
        ),
    ]
