# Generated by Django 5.1.6 on 2025-03-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_remove_sample_test_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="lab.sample",
            ),
        ),
    ]
