# Generated by Django 6.0rc1 on 2026-05-12 10:30

from django.db import migrations, models


def forwards_consanguinity_values(apps, schema_editor):
    for model_name in ("Family", "HistoricalFamily"):
        Model = apps.get_model("lab", model_name)
        for obj in Model.objects.all():
            value = obj.is_consanguineous
            normalized = str(value).lower() if value is not None else ""
            if normalized in {"true", "1"}:
                obj.is_consanguineous = "consanguineous"
            elif normalized in {"false", "0"}:
                obj.is_consanguineous = "non_consanguineous"
            else:
                obj.is_consanguineous = value or None
            obj.save(update_fields=["is_consanguineous"])


def reverse_consanguinity_values(apps, schema_editor):
    for model_name in ("Family", "HistoricalFamily"):
        Model = apps.get_model("lab", model_name)
        for obj in Model.objects.all():
            if obj.is_consanguineous == "consanguineous":
                obj.is_consanguineous = True
            elif obj.is_consanguineous == "non_consanguineous":
                obj.is_consanguineous = False
            else:
                obj.is_consanguineous = None
            obj.save(update_fields=["is_consanguineous"])


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_identifier_type_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='is_consanguineous',
            field=models.CharField(blank=True, choices=[('non_consanguineous', 'Non-Consanguineous'), ('mildly_consanguineous', 'Mildly Consanguineous'), ('consanguineous', 'Consanguineous')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfamily',
            name='is_consanguineous',
            field=models.CharField(blank=True, choices=[('non_consanguineous', 'Non-Consanguineous'), ('mildly_consanguineous', 'Mildly Consanguineous'), ('consanguineous', 'Consanguineous')], max_length=24, null=True),
        ),
        migrations.RunPython(forwards_consanguinity_values, reverse_consanguinity_values),
    ]
