# Generated by Django 6.0rc1 on 2026-05-12 10:59

import re

from django.db import migrations, models


def parse_age_of_onset_in_months(age_of_onset):
    if not age_of_onset:
        return None

    tokens = [
        token.strip().strip(".,;:()[]{}").lower()
        for token in str(age_of_onset).split()
    ]
    year_tokens = {"year", "years", "yıl", "yaş"}
    month_tokens = {"month", "months", "ay", "aylık"}

    multiplier = None
    if any(token in year_tokens for token in tokens):
        multiplier = 12
    elif any(token in month_tokens for token in tokens):
        multiplier = 1

    if multiplier is None:
        return None

    for token in tokens:
        normalized = token.replace(",", ".")
        if re.fullmatch(r"-?\d+(?:\.\d+)?", normalized):
            return int(float(normalized) * multiplier)

    return None


def backfill_age_of_onset_in_months(apps, schema_editor):
    for model_name in ("Individual", "HistoricalIndividual"):
        Model = apps.get_model("lab", model_name)
        for obj in Model.objects.all().only("pk", "age_of_onset"):
            obj.age_of_onset_in_months = parse_age_of_onset_in_months(
                obj.age_of_onset
            )
            obj.save(update_fields=["age_of_onset_in_months"])


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_family_consanguinity_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindividual',
            name='age_of_onset_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='age_of_onset_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_age_of_onset_in_months, migrations.RunPython.noop),
    ]
