# Generated by Django 6.0rc1 on 2025-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_preferences',
            field=models.JSONField(default=dict, help_text='UI and display preference settings'),
        ),
    ]
