# Generated by Django 5.1.6 on 2025-03-14 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0005_test_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SampleTestAnalysis",
            new_name="Analysis",
        ),
        migrations.AlterModelOptions(
            name="analysis",
            options={"ordering": ["-created_at"], "verbose_name_plural": "analyses"},
        ),
    ]
