# Generated by Codex on 2026-05-21

from django.db import migrations, models


def forwards_consanguinity_values(apps, schema_editor):
    for model_name in ("Family", "HistoricalFamily"):
        Model = apps.get_model("lab", model_name)
        for obj in Model.objects.all():
            value = obj.is_consanguineous
            normalized = str(value).strip().lower() if value is not None else ""
            if value is True or normalized in {"true", "1", "consanguineous"}:
                obj.is_consanguineous = True
            elif value is False or normalized in {"false", "0", "non_consanguineous"}:
                obj.is_consanguineous = False
            else:
                obj.is_consanguineous = None
            obj.save(update_fields=["is_consanguineous"])


def reverse_consanguinity_values(apps, schema_editor):
    for model_name in ("Family", "HistoricalFamily"):
        Model = apps.get_model("lab", model_name)
        for obj in Model.objects.all():
            value = obj.is_consanguineous
            normalized = str(value).strip().lower() if value is not None else ""
            if value is True or normalized in {"true", "1"}:
                obj.is_consanguineous = "consanguineous"
            elif value is False or normalized in {"false", "0"}:
                obj.is_consanguineous = "non_consanguineous"
            else:
                obj.is_consanguineous = None
            obj.save(update_fields=["is_consanguineous"])


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_individual_age_of_onset_months"),
    ]

    operations = [
        migrations.RunPython(forwards_consanguinity_values, reverse_consanguinity_values),
        migrations.AlterField(
            model_name="family",
            name="is_consanguineous",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfamily",
            name="is_consanguineous",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
