# Generated by Django 6.0rc1 on 2026-02-10 13:17
# Amended: added RunPython data migrations so that existing AnalysisType rows
# are carried forward as PipelineType, and existing Analysis rows are carried
# forward as Pipeline, before the old foreign-key columns are dropped.

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Data-migration helpers
# ---------------------------------------------------------------------------

def migrate_to_pipelines(apps, schema_editor):
    """
    Two-step data migration run before the old columns are removed:

    Step 1 – AnalysisType → PipelineType
        The two models are structurally identical (name, description, version,
        source_url, results_url, created_by, parent_types M2M).  We create a
        matching PipelineType for every AnalysisType and restore the M2M tree.

    Step 2 – Analysis → Pipeline
        The old Analysis held the fields that Pipeline now holds (test, dates,
        performed_by, status, type).  We create one Pipeline per Analysis and
        immediately point analysis.pipeline at it.  Downstream migrations
        (variant/0003) then copy variant.analysis.pipeline → variant.pipeline
        before the analysis FK is dropped.
    """
    AnalysisType = apps.get_model("lab", "AnalysisType")
    PipelineType = apps.get_model("lab", "PipelineType")
    Analysis = apps.get_model("lab", "Analysis")
    Pipeline = apps.get_model("lab", "Pipeline")

    # Step 1a: create one PipelineType per AnalysisType ----------------------
    at_to_pt = {}
    for at in AnalysisType.objects.all():
        pt = PipelineType(
            name=at.name,
            description=at.description,
            version=at.version,
            source_url=at.source_url,
            results_url=at.results_url,
            created_by_id=at.created_by_id,
        )
        pt.save()
        at_to_pt[at.pk] = pt

    # Step 1b: restore parent_types M2M after all PipelineType rows exist ----
    for at in AnalysisType.objects.prefetch_related("parent_types").all():
        pt = at_to_pt[at.pk]
        for parent in at.parent_types.all():
            parent_pt = at_to_pt.get(parent.pk)
            if parent_pt:
                pt.parent_types.add(parent_pt)

    # Step 2: create one Pipeline per Analysis --------------------------------
    for analysis in Analysis.objects.all():
        pt = at_to_pt.get(analysis.type_id)
        pipeline = Pipeline(
            test_id=analysis.test_id,
            performed_date=analysis.performed_date,
            performed_by_id=analysis.performed_by_id,
            status_id=analysis.status_id,
            created_by_id=analysis.created_by_id,
            type=pt,
        )
        pipeline.save()
        # Use update() to avoid triggering signal overhead on every row
        Analysis.objects.filter(pk=analysis.pk).update(pipeline_id=pipeline.pk)


def reverse_noop(apps, schema_editor):
    """
    Reverse of this migration is intentionally a no-op.
    Restoring the original FK values from the new structure is not possible
    without a separate backup, so rolling back is not supported.
    """


# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_profile_display_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. Create PipelineType (and its audit table) so the data
        #       migration has a destination table to write into.
        migrations.CreateModel(
            name="HistoricalPipelineType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the pipeline source code or documentation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "results_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to view pipeline results",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pipeline type",
                "verbose_name_plural": "historical pipeline types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PipelineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the pipeline source code or documentation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "results_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to view pipeline results",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pipeline_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_types",
                    models.ManyToManyField(
                        blank=True, related_name="subtypes", to="lab.pipelinetype"
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-version"],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        # ── 2. Create Pipeline (with type FK already present so the data
        #       migration can insert fully-populated rows in one pass).
        #       The table starts empty, so the NOT-NULL type FK is fine.
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pipelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="lab.status"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pipelines",
                        to="lab.test",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.pipelinetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pipelines",
                "ordering": ["-id"],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPipeline",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("performed_date", models.DateField()),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lab.status",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lab.test",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lab.pipelinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pipeline",
                "verbose_name_plural": "historical pipelines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # ── 3. Add analysis.pipeline FK (nullable) so the data migration
        #       can populate it before the old columns are removed.
        migrations.AddField(
            model_name="analysis",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analyses",
                to="lab.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="lab.pipeline",
            ),
        ),
        # ── 4. THE DATA MIGRATION ─────────────────────────────────────────
        #       Copies AnalysisType → PipelineType and Analysis → Pipeline,
        #       and sets analysis.pipeline on every existing row.
        #       Only after this step are the old columns safe to drop.
        migrations.RunPython(migrate_to_pipelines, reverse_noop),
        # ── 5. Now the old columns can be dropped safely ──────────────────
        migrations.RemoveField(
            model_name="analysis",
            name="type",
        ),
        migrations.RemoveField(
            model_name="historicalanalysis",
            name="type",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="test",
        ),
        migrations.RemoveField(
            model_name="historicalanalysis",
            name="test",
        ),
        # FK columns on HistoricalAnalysisType must be cleared before the
        # model itself is deleted (Django requires this for history tables).
        migrations.RemoveField(
            model_name="historicalanalysistype",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalanalysistype",
            name="history_user",
        ),
        # ── 6. Unrelated model / field changes ────────────────────────────
        migrations.AlterModelOptions(
            name="individual",
            options={
                "ordering": ["-id"],
                "permissions": [
                    ("view_sensitive_data", "Can view sensitive data")
                ],
            },
        ),
        migrations.AlterField(
            model_name="analysis",
            name="performed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="performed_date",
            field=models.DateField(blank=True, null=True),
        ),
        # ── 7. Delete old models ──────────────────────────────────────────
        migrations.DeleteModel(
            name="AnalysisType",
        ),
        migrations.DeleteModel(
            name="HistoricalAnalysisType",
        ),
    ]
