# Generated by Django 6.0rc1 on 2025-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_analysisrequestform_historicalanalysisrequestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequestform',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='analysis_requests/previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='historicalanalysisrequestform',
            name='preview_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
