# Generated by Django 5.1.6 on 2025-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_rename_sampletestanalysis_to_analysis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="sample_test",
            new_name="test",
        ),
        migrations.AlterField(
            model_name="analysistype",
            name="version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
