# Generated by Django 6.0rc1 on 2026-02-10 13:17

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_profile_display_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalanalysis',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalanalysistype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalanalysistype',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-id'], 'permissions': [('view_sensitive_data', 'Can view sensitive data')]},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='test',
        ),
        migrations.RemoveField(
            model_name='historicalanalysis',
            name='test',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPipelineType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL to the pipeline source code or documentation', max_length=500, null=True)),
                ('results_url', models.URLField(blank=True, help_text='URL to view pipeline results', max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pipeline type',
                'verbose_name_plural': 'historical pipeline types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.status')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='lab.test')),
            ],
            options={
                'verbose_name_plural': 'pipelines',
                'ordering': ['-id'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.AddField(
            model_name='analysis',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='lab.pipeline'),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipeline'),
        ),
        migrations.CreateModel(
            name='PipelineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL to the pipeline source code or documentation', max_length=500, null=True)),
                ('results_url', models.URLField(blank=True, help_text='URL to view pipeline results', max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pipeline_types', to=settings.AUTH_USER_MODEL)),
                ('parent_types', models.ManyToManyField(blank=True, related_name='subtypes', to='lab.pipelinetype')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.pipelinetype'),
        ),
        migrations.CreateModel(
            name='HistoricalPipeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('performed_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status')),
                ('test', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.test')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.pipelinetype')),
            ],
            options={
                'verbose_name': 'historical pipeline',
                'verbose_name_plural': 'historical pipelines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='AnalysisType',
        ),
        migrations.DeleteModel(
            name='HistoricalAnalysisType',
        ),
    ]
