# Generated by Django 5.1.6 on 2025-03-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_rename_analysis_sample_test_to_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_as_father",
                to="lab.individual",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_as_mother",
                to="lab.individual",
            ),
        ),
    ]
