# Generated by Django 5.1.6 on 2025-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0008_individual_father_individual_mother"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="icd11_code",
            field=models.TextField(blank=True),
        ),
    ]
