# Generated by Django 5.1.6 on 2024-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_update_test_model"),
        ("lab", "0009_alter_individual_icd11_code"),
    ]

    operations = [] 