# Generated by Django 5.1.6 on 2025-03-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0010_merge_20240320_1234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="council_date",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="data_receipt_date",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="service_send_date",
        ),
        migrations.AddField(
            model_name="individual",
            name="council_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="sending_institution",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.institution",
            ),
            preserve_default=False,
        ),
    ]
