# Generated by Django 6.0rc1 on 2026-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_analysis_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidentifiertype',
            name='is_shown_in_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalidentifiertype',
            name='use_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='identifiertype',
            name='is_shown_in_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='identifiertype',
            name='use_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='crossidentifier',
            unique_together={('individual', 'id_type')},
        ),
    ]
