# Generated by Django 6.0rc1 on 2026-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_historicalidentifiertype_is_shown_in_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='short_name',
            field=models.CharField(blank=True, help_text='Optional abbreviated label shown in table badges (falls back to full name).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='short_name',
            field=models.CharField(blank=True, help_text='Optional abbreviated label shown in table badges (falls back to full name).', max_length=30, null=True),
        ),
    ]
