# Generated by Django 6.0rc1 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_add_status_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpipeline',
            name='input_location',
            field=models.TextField(blank=True, help_text='Path to the input file(s) used by this pipeline run'),
        ),
        migrations.AddField(
            model_name='historicalpipeline',
            name='output_location',
            field=models.TextField(blank=True, help_text='Path to the output directory or file(s) produced by this pipeline run'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='input_location',
            field=models.TextField(blank=True, help_text='Path to the input file(s) used by this pipeline run'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='output_location',
            field=models.TextField(blank=True, help_text='Path to the output directory or file(s) produced by this pipeline run'),
        ),
    ]
