# Generated by Django 6.0rc1 on 2026-03-09

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


def migrate_status_fk_to_tags(apps, schema_editor):
    """Copy existing FK status values to the new TaggedStatus M2M through table."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    TaggedStatus = apps.get_model("lab", "TaggedStatus")

    model_names = [
        ("lab", "individual"),
        ("lab", "sample"),
        ("lab", "test"),
        ("lab", "pipeline"),
        ("lab", "analysis"),
        ("lab", "task"),
        ("lab", "project"),
    ]

    for app_label, model_name in model_names:
        try:
            Model = apps.get_model(app_label, model_name)
            ct = ContentType.objects.get_for_model(Model)
        except Exception:
            continue

        for obj in Model.objects.filter(status__isnull=False):
            try:
                TaggedStatus.objects.get_or_create(
                    content_type=ct,
                    object_id=obj.pk,
                    tag=obj.status,
                )
            except Exception:
                pass

    # Migrate Variant status too
    try:
        Variant = apps.get_model("variant", "variant")
        variant_ct = ContentType.objects.get_for_model(Variant)
        for v in Variant.objects.filter(status__isnull=False):
            try:
                TaggedStatus.objects.get_or_create(
                    content_type=variant_ct,
                    object_id=v.pk,
                    tag=v.status,
                )
            except Exception:
                pass
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lab', '0013_pipeline_add_locations'),
    ]

    operations = [
        # 1. Alter previous_status help text first (no data impact)
        migrations.AlterField(
            model_name='historicaltask',
            name='previous_status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Stores the primary task status before it was last completed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='previous_status',
            field=models.ForeignKey(blank=True, help_text='Stores the primary task status before it was last completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_previous_status', to='lab.status'),
        ),
        # 2. Create the new TaggedStatus through model
        migrations.CreateModel(
            name='TaggedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='lab.status')),
            ],
            options={
                'verbose_name': 'Tagged Status',
                'verbose_name_plural': 'Tagged Statuses',
                'unique_together': {('content_type', 'object_id', 'tag')},
            },
        ),
        # 3. Add the TaggableManager fields (virtual, no DB columns)
        migrations.AddField(
            model_name='analysis',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='individual',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='project',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='sample',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='task',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        migrations.AddField(
            model_name='test',
            name='statuses',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lab.TaggedStatus', to='lab.Status', verbose_name='Statuses'),
        ),
        # 4. Data migration: copy existing FK status values to the M2M table
        migrations.RunPython(
            migrate_status_fk_to_tags,
            reverse_code=migrations.RunPython.noop,
        ),
        # 5. Remove the old status FK fields
        migrations.RemoveField(model_name='analysis', name='status'),
        migrations.RemoveField(model_name='historicalanalysis', name='status'),
        migrations.RemoveField(model_name='historicalindividual', name='status'),
        migrations.RemoveField(model_name='historicalpipeline', name='status'),
        migrations.RemoveField(model_name='historicalproject', name='status'),
        migrations.RemoveField(model_name='historicalsample', name='status'),
        migrations.RemoveField(model_name='historicaltask', name='status'),
        migrations.RemoveField(model_name='historicaltest', name='status'),
        migrations.RemoveField(model_name='individual', name='status'),
        migrations.RemoveField(model_name='pipeline', name='status'),
        migrations.RemoveField(model_name='project', name='status'),
        migrations.RemoveField(model_name='sample', name='status'),
        migrations.RemoveField(model_name='task', name='status'),
        migrations.RemoveField(model_name='test', name='status'),
    ]
