# Generated by Django 6.0rc1 on 2026-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_remove_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='group',
            field=models.CharField(blank=True, help_text='Statuses sharing the same group name are mutually exclusive — selecting one removes the others from this group.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='group',
            field=models.CharField(blank=True, help_text='Statuses sharing the same group name are mutually exclusive — selecting one removes the others from this group.', max_length=100, null=True),
        ),
    ]
