# Generated by Django 6.0rc1 on 2026-03-09 13:39

import django.db.models.deletion
import lab.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lab', '0015_status_add_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStatusGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Status Group',
                'verbose_name_plural': 'historical Status Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Status Group',
                'verbose_name_plural': 'Status Groups',
                'ordering': ['content_type__model', 'name'],
                'unique_together': {('name', 'content_type')},
            },
            bases=(lab.models.HistoryMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Statuses in the same group are mutually exclusive — selecting one removes the others.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.statusgroup'),
        ),
        migrations.AlterField(
            model_name='status',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Statuses in the same group are mutually exclusive — selecting one removes the others.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='lab.statusgroup'),
        ),
    ]
