from django.urls import path
from .views import (
    DashboardView,
    IndividualListView,
    ProjectListView,
    SampleListView,
    IndividualDetailView,
    ProjectDetailView,
    TaskDetailView,
    VariantListView,
    FamilyCreateView,
    HPOTermSearchView,
    hpo_bulk_match,
    RenderSelectedHPOTermView,
    CompleteTaskView,
    ReopenTaskView,
    IndividualExportView,
    configurations_view,
    MapVisualizationView,
    issue_plot_token_view,
    generic_plot_data,
    PlotGalleryView,
    add_widget,
    remove_widget,
    reorder_widgets,
    list_notebook_files,
    preview_plot_data,
    marimo_proxy,
    marimo_run_proxy,
)
from .profile_views import ProfileView, UpdateThemeView, UpdateFontSizeView, UpdateInstitutionDisplayView
from .htmx_views import (
    RevealSensitiveFieldView,
    add_individual_row,
    IndividualHPOEditView,
    manage_hpo_term,
    note_create,
    note_update,
    note_delete,
    note_list,
    note_count,
    individual_identification_edit,
    individual_identification_save,
    individual_demographics_edit,
    individual_demographics_save,
    individual_identification_display,
    individual_demographics_display,
    individual_contact_information_display,
    individual_contact_information_edit,
    individual_contact_information_save,
    family_search,
    individual_parents_edit,
    individual_parents_display,
    individual_parents_save,
    individual_toggle_index,
    individual_toggle_affected,
    family_id_edit,
    family_id_save,
    family_manage_members,
    family_add_member,
    family_remove_member,
    individual_family_section,
    individual_clinical_summary_edit,
    individual_clinical_summary_save,
    individual_clinical_summary_display,
    individual_age_of_onset_months_edit,
    individual_age_of_onset_months_save,
    individual_age_of_onset_months_display,
    update_status,
    sample_create_modal,
    test_create_modal,
    task_create_modal,
    pipeline_create_modal,
    analysis_create_modal,
    individual_projects_edit,
    individual_projects_save,
    project_search,
    project_individual_search,
    project_individual_add,
    project_individual_remove,
    project_individuals_page,
    project_tasks_page,
    task_detail_edit,
    task_detail_save,
    document_preview,
    document_download,
    project_create_modal,
    project_delete_modal,
    request_form_create_modal,
    report_create_modal,
    generate_analysis_report_docx,
    report_replace_modal,
    workflow_delete_confirm,
    workflow_delete,
    variant_create_modal,
    variant_detail_partial,
    variant_genebe_fetch,
    variant_acmg_evidence_save,
    config_form,
    config_delete_confirm,
    config_delete,
    config_section_partial,
)


app_name = "lab"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("individuals/", IndividualListView.as_view(), name="individual_list"),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path("projects/<int:pk>/detail/", ProjectDetailView.as_view(), name="project_detail"),
    path("variants/", VariantListView.as_view(), name="variant_list"),
    # Map visualization (current and default at /visualizations/)
    path("visualizations/", MapVisualizationView.as_view(), name="map_visualization"),
    path("individuals/export/", IndividualExportView.as_view(), name="individual_export"),
    path("individuals/create-family/", FamilyCreateView.as_view(), name="create_family"),
    path("samples/", SampleListView.as_view(), name="sample_list"),
    path("individuals/<int:pk>/detail/", IndividualDetailView.as_view(), name="individual_detail"),
    path("reveal/<str:model_name>/<int:pk>/<str:field_name>/", RevealSensitiveFieldView.as_view(), name="reveal_sensitive_field"),
    path("htmx/add-individual-row/", add_individual_row, name="add_individual_row"),
    path("htmx/individual/<int:pk>/hpo-edit/", IndividualHPOEditView.as_view(), name="hpo_edit"),
    path("htmx/individual/<int:pk>/hpo-manage/", manage_hpo_term, name="hpo_manage"),
    
    # Inline Edit
    path("htmx/individual/<int:pk>/identification/", individual_identification_display, name="individual_identification_display"),
    path("htmx/individual/<int:pk>/identification/edit/", individual_identification_edit, name="individual_identification_edit"),
    path("htmx/individual/<int:pk>/identification/save/", individual_identification_save, name="individual_identification_save"),
    path("htmx/individual/<int:pk>/demographics/", individual_demographics_display, name="individual_demographics_display"),
    path("htmx/individual/<int:pk>/demographics/edit/", individual_demographics_edit, name="individual_demographics_edit"),
    path("htmx/individual/<int:pk>/demographics/save/", individual_demographics_save, name="individual_demographics_save"),
    path("htmx/individual/<int:pk>/contact-information/", individual_contact_information_display, name="individual_contact_information_display"),
    path("htmx/individual/<int:pk>/contact-information/edit/", individual_contact_information_edit, name="individual_contact_information_edit"),
    path("htmx/individual/<int:pk>/contact-information/save/", individual_contact_information_save, name="individual_contact_information_save"),
    path("htmx/family/search/", family_search, name="family_search"),
    path("htmx/individual/<int:pk>/parents/edit/", individual_parents_edit, name="individual_parents_edit"),
    path("htmx/individual/<int:pk>/parents/display/", individual_parents_display, name="individual_parents_display"),
    path("htmx/individual/<int:pk>/parents/save/", individual_parents_save, name="individual_parents_save"),
    path("htmx/individual/<int:pk>/toggle-index/", individual_toggle_index, name="individual_toggle_index"),
    path("htmx/individual/<int:pk>/toggle-affected/", individual_toggle_affected, name="individual_toggle_affected"),
    path("htmx/family/<int:pk>/edit-id/", family_id_edit, name="family_id_edit"),
    path("htmx/family/<int:pk>/save-id/", family_id_save, name="family_id_save"),
    path("htmx/family/<int:pk>/manage-members/", family_manage_members, name="family_manage_members"),
    path("htmx/family/<int:pk>/add-member/", family_add_member, name="family_add_member"),
    path("htmx/family/member/<int:pk>/remove/", family_remove_member, name="family_remove_member"),
    path("htmx/individual/<int:pk>/family-section/", individual_family_section, name="individual_family_section"),
    path("htmx/individual/<int:pk>/clinical-summary/", individual_clinical_summary_display, name="individual_clinical_summary_display"),
    path("htmx/individual/<int:pk>/clinical-summary/edit/", individual_clinical_summary_edit, name="individual_clinical_summary_edit"),
    path("htmx/individual/<int:pk>/clinical-summary/save/", individual_clinical_summary_save, name="individual_clinical_summary_save"),
    path("htmx/individual/<int:pk>/age-of-onset-months/", individual_age_of_onset_months_display, name="individual_age_of_onset_months_display"),
    path("htmx/individual/<int:pk>/age-of-onset-months/edit/", individual_age_of_onset_months_edit, name="individual_age_of_onset_months_edit"),
    path("htmx/individual/<int:pk>/age-of-onset-months/save/", individual_age_of_onset_months_save, name="individual_age_of_onset_months_save"),

    # HPO Search
    path("htmx/hpo/search/", HPOTermSearchView.as_view(), name="hpo_search"),
    path("htmx/hpo/bulk-match/", hpo_bulk_match, name="hpo_bulk_match"),
    path("htmx/hpo/picker/", HPOTermSearchView.as_view(template_name="lab/partials/hpo_picker_results.html"), name="hpo_picker"),
    path("htmx/hpo/render/<int:pk>/", RenderSelectedHPOTermView.as_view(), name="render_selected_hpo"),
    
    # Notes
    path("htmx/notes/create/", note_create, name="note_create"),
    path("htmx/notes/update/<int:pk>/", note_update, name="note_update"),
    path("htmx/notes/delete/<int:pk>/", note_delete, name="note_delete"),
    path("htmx/notes/list/", note_list, name="note_list"),
    path("htmx/notes/count/", note_count, name="note_count"),
    
    # Profile & Theme
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/update-theme/", UpdateThemeView.as_view(), name="update_theme"),
    path("profile/update-font-size/", UpdateFontSizeView.as_view(), name="update_font_size"),
    path("profile/update-institution-display/", UpdateInstitutionDisplayView.as_view(), name="update_institution_display"),
    
    # Status Updates
    path(
        "status/update/<int:content_type_id>/<int:object_id>/<int:status_id>/",
        update_status,
        name="update_status",
    ),
    path("htmx/sample/create/<int:individual_id>/", sample_create_modal, name="sample_create_modal"),
    path("htmx/test/create/<int:sample_id>/", test_create_modal, name="test_create_modal"),
    path("htmx/pipeline/create/<int:test_id>/", pipeline_create_modal, name="pipeline_create_modal"),
    path("htmx/analysis/create/<int:pipeline_id>/", analysis_create_modal, name="analysis_create_modal"),
    path("htmx/task/create/<int:content_type_id>/<int:object_id>/", task_create_modal, name="task_create_modal"),
    path("htmx/request_form/create/<int:individual_id>/", request_form_create_modal, name="request_form_create_modal"),
    path("htmx/report/create/<int:analysis_id>/", report_create_modal, name="report_create_modal"),
    path("htmx/report/generate/<int:analysis_id>/", generate_analysis_report_docx, name="analysis_report_generate"),
    path("htmx/report/<int:report_id>/replace/", report_replace_modal, name="report_replace_modal"),
    path("htmx/workflow/<str:model_name>/<int:pk>/delete-confirm/", workflow_delete_confirm, name="workflow_delete_confirm"),
    path("htmx/workflow/<str:model_name>/<int:pk>/delete/", workflow_delete, name="workflow_delete"),
    path("htmx/variant/create/analysis/<int:analysis_id>/", variant_create_modal, name="variant_create_for_analysis_modal"),
    path("htmx/variant/create/individual/<int:individual_id>/", variant_create_modal, name="variant_create_for_individual_modal"),
    path("htmx/variant/<int:pk>/genebe-fetch/", variant_genebe_fetch, name="variant_genebe_fetch"),
    path("htmx/variant/<int:pk>/acmg-evidence/", variant_acmg_evidence_save, name="variant_acmg_evidence_save"),
    
    # Project Management
    path("htmx/individual/<int:pk>/projects/edit/", individual_projects_edit, name="individual_projects_edit"),
    path("htmx/individual/<int:pk>/projects/save/", individual_projects_save, name="individual_projects_save"),
    path("htmx/project/search/", project_search, name="project_search"),
    path("htmx/project/<int:pk>/individuals/search/", project_individual_search, name="project_individual_search"),
    path("htmx/project/<int:project_pk>/individuals/<int:individual_pk>/add/", project_individual_add, name="project_individual_add"),
    path("htmx/project/<int:project_pk>/individuals/<int:individual_pk>/remove/", project_individual_remove, name="project_individual_remove"),
    path("htmx/project/<int:pk>/individuals/page/", project_individuals_page, name="project_individuals_page"),
    path("htmx/project/<int:pk>/tasks/", project_tasks_page, name="project_tasks_page"),
    path("htmx/project/create/", project_create_modal, name="project_create_modal"),
    path("htmx/project/<int:pk>/delete/", project_delete_modal, name="project_delete_modal"),
    path("tasks/<int:pk>/detail/", TaskDetailView.as_view(), name="task_detail"),
    path("htmx/task/complete/<int:pk>/", CompleteTaskView.as_view(), name="complete_task"),
    path("htmx/task/reopen/<int:pk>/", ReopenTaskView.as_view(), name="reopen_task"),
    path("htmx/task/<int:pk>/edit/", task_detail_edit, name="task_detail_edit"),
    path("htmx/task/<int:pk>/save/", task_detail_save, name="task_detail_save"),
    path("htmx/preview/<str:model_name>/<int:pk>/", document_preview, name="document_preview"),
    path("documents/<str:model_name>/<int:pk>/download/", document_download, name="document_download"),
    path("htmx/variant/<int:pk>/detail/", variant_detail_partial, name="variant_detail_partial"),

    # Configurations
    path("configurations/", configurations_view, name="configurations"),
    path("htmx/config/<str:model_name>/section/", config_section_partial, name="config_section"),
    path("htmx/config/<str:model_name>/form/", config_form, name="config_form_add"),
    path("htmx/config/<str:model_name>/<int:pk>/form/", config_form, name="config_form_edit"),
    path("htmx/config/<str:model_name>/<int:pk>/delete-confirm/", config_delete_confirm, name="config_delete_confirm"),
    path("htmx/config/<str:model_name>/<int:pk>/delete/", config_delete, name="config_delete"),
    
    # API for Marimo
    path("api/plot-token/", issue_plot_token_view, name="issue_plot_token"),
    path("api/plot-data/", generic_plot_data, name="generic_plot_data"),
    # Dashboard Integrations
    path("gallery/", PlotGalleryView.as_view(), name="plot_gallery"),
    path("dashboard/add/<int:pk>/", add_widget, name="add_widget"),
    path("dashboard/remove/<int:pk>/", remove_widget, name="remove_widget"),
    path("dashboard/reorder/", reorder_widgets, name="reorder_widgets"),
    
    # Phase 5: Admin Authoring UX
    path("authoring/notebooks/", list_notebook_files, name="list_notebooks"),
    path("authoring/preview-plot/", preview_plot_data, name="preview_plot_data"),
    path("authoring/marimo/", marimo_proxy, name="marimo_proxy"),
    path("authoring/marimo/<path:path>", marimo_proxy, name="marimo_proxy_path"),
    path("authoring/marimo-run/", marimo_run_proxy, name="marimo_run_proxy"),
]
